### ISSUE TITLE
Unable to install with atom v0.196

### ISSUE THREAD

**Issue by KINFOO** [bichiliad/atom-jsfmt#11]
Hi,

When I try to install `atom-jsfmt` in __Atom v 0.196__, I get:

![atom](https://cloud.githubusercontent.com/assets/154818/7468875/bc5ec9d4-f30d-11e4-8130-1d9bc4299a34.png)

It would be nice to be able to install it again.

Kevin

**Comment by BrianSipple** [comment]
+1

**Comment by MethodGrab** [comment]
:+1: 
Is this project still maintained? It doesn't look like it's been updated in 12 months.

**Comment by zia-newversion** [comment]
+1. Now on Atom v0.200.0

**Comment by bichiliad** [comment]
Not sure why I haven't seen this yet. I'm working on an update to remove deprecated code, and will likely move to atom-message-panel. 

(Sorry for the lack of commits, was finishing school)

**Comment by MethodGrab** [comment]
Good to hear, thanks for the update!

**Comment by zia-newversion** [comment]
:+1:

**Comment by bichiliad** [comment]
I pushed an update and then promptly left for vacation, but this plugin should be installable (and working properly) again. Feel free to open a new ticket if there's any other funkiness going on.
