### ISSUE TITLE
Failed to load the atom-jsfmt package

### ISSUE THREAD

**Issue by ckaemper** [bichiliad/atom-jsfmt#21]
After updating to 0.8.4 I get the following error.

Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

I'm using Atom 1.5.3 on Windows 7 64 Bit. Please find the error report attached.
[error-report.txt](https://github.com/bichiliad/atom-jsfmt/files/130347/error-report.txt)

Thanks for the great plugin.
Christian

**Comment by bichiliad** [comment]
This is a duplicate of #20 - I'm looking into it now. Closing this as a duplicate.

**Comment by bichiliad** [comment]
Ugh sorry - reopening, since #20 is a PR and this is an issue.

**Comment by ckaemper** [comment]
With the update to 0.8.5 it works for me again.

Thanks a bunch @bichiliad and @mikaa123 for fixing this so quickly.
