### ISSUE TITLE
Support .jsfmtrc files

### ISSUE THREAD

**Issue by svizzari** [bichiliad/atom-jsfmt#7]
Your TODO in the README

> Allow for input of custom rules

probably covers this, but, thought I'd call it out specifically :smile_cat: 

Thanks

**Comment by bichiliad** [comment]
I just pushed v0.8.0. Whenever you try to format a file, atom-jsfmt will look for the closest .jsfmtrc file (if any) and use it to configure the formatter. As always, let me know if you see any weirdness with it.
